services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7
    command: ["redis-server", "--save", "", "--appendonly", "no",
              "--maxmemory", "${REDIS_MAXMEMORY}",
              "--maxmemory-policy", "${REDIS_POLICY}"]
    # Si quieres exponer a tu PC, descomenta:
    # ports:
    #   - "6379:6379"

  storage-api:
    build: ./services/storage-api
    env_file: [.env]
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8001:8001"
    volumes:
      - ./data:/data:ro

  cache-service:
    build: ./services/cache-service
    env_file: [.env]
    depends_on:
      - redis
    ports:
      - "8002:8002"
  responder-llm:
    build: ./services/responder-llm
    env_file: [.env]
    ports:
      - "8003:8003"
  scorer:
    build: ./services/scorer
    env_file: [.env]
    ports:
      - "8004:8004"



volumes:
  pgdata:
